tokens:
  certificatepath: certs/localhost.crt
  privatekeypath: certs/localhost.key
  issuer: https://localhost:5000
  lifetime: 00:01:00
users:
  - username: root
    plain_text_password: superuser
    acl: [ admin ]
  - username: localhostUser
    ip: 127.0.0.1:*
    acl: [ pull-any ]

acl:
  - name: admin
    access:
      - type: registry
        name: '*'
        actions: [ '*' ]
      - type: repository
        name: '**/*'
        actions: [ '*' ]
  - name: pull-any
    access:
      - type: repository
        name: '*'
        actions: [ pull ]