on: [push]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - run: dotnet tool restore
      - run: dotnet cake --target build --configuration Release
      - run: dotnet cake --target artifacts/pkg --configuration Release --no-build
      - run: dotnet cake --target artifacts/lib --configuration Release --no-build
    permissions:
      actions: write
