on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-dotnet@v3
      - run: dotnet tool restore
      - run: ./build.ps1 --target build --configuration Release
        shell: pwsh
      - run: ./build.ps1 --target pack --configuration Release --no-build
        shell: pwsh
      - uses: actions/upload-artifact@v3
        with:
          path: |
            artifacts/pkg/*.nupkg
            artifacts/pkg/*.snupkg
          name: packages
      - uses: actions/upload-artifact@v3
        with:
          path: artifacts/lib/*.zip
          name: libraries
