on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - run: dotnet tool restore
      - name: Build projects
        run: dotnet cake --target build --configuration Release
      - name: Create zip archives
        run: dotnet cake --target lib --exclusive
      - uses: actions/upload-artifact@v3
        with:
          path: ./artifacts/lib/**
