on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-dotnet@v3
      - run: ./build.ps1 -t build -c Release -v Verbose
        shell: pwsh
      - uses: actions/upload-artifact@v3
        with:
          path: |
            artifacts/pkg/*.nupkg
            artifacts/pkg/*.snupkg
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-dotnet@v3
      - run: ./build.ps1 -t test -c Debug -v Verbose
        shell: pwsh
  push-packages:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-dotnet@v3
      - uses: actions/download-artifact@v3
        with: { path: artifacts/pkg, name: packages }
      - run: ./build.ps1 --target artifacts/push/nuget
        shell: pwsh
