on: [push, pull_request]
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [common, core]
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-dotnet@v3
      - run: >-
          ./build.ps1 --target :${{ matrix.target }}.tests:test --configuration Release
          --no-copy-artifacts
        shell: powershell
